import candycane from "./assets/candycane_red_bg_square.jpg"

 export default [
    {
        id: 0,
        title: "Sweet Treat",
        description: "Ten assorted candies per month",
        price: 10,
        picture: candycane,
        alttext: "a red and white striped candy canes scattered across a red background",
        box: true,
        max_quantity: 1,
    },
    {
        id: 1,
        title: "Chocolatier",
        description: "Three chocalate bars created by our in house chef",
        price: 15,
        picture: candycane,
        alttext: "a red and white striped candy canes scattered across a red background",
        box: true,
        max_quantity: 1,
    },
    {
        id: 2,
        title: "Candy Mountain",
        description:  "30 assorted candies per month",
        price: 25,
        picture: candycane,
        alttext: "a red and white striped candy canes scattered across a red background",
        box: true,
        max_quantity: 1,
    },
    {
        id: 3,
        title: "Candy Cane",
        description: "A classic treat sweet minty flavor",
        price: 2,
        picture: candycane,
        alttext: "a red and white striped candy canes scattered across a red background",
        box: false,
        max_quantity: 25,
    },
    {
        id: 4,
        title: "test candy 1",
        description: "mystery candy (dairy-free)",
        price: 1,
        picture: candycane,
        alttext: "a red and white striped candy canes scattered across a red background",
        box: false,
        max_quantity: 50,
    },
    {
        id: 5,
        title: "test candy 2",
        description: "mystery candy (dairy-free)",
        price: 1,
        picture: candycane,
        alttext: "a red and white striped candy canes scattered across a red background",
        box: false,
        max_quantity: 32,
    },
    {
        id: 6,
        title: "test candy 3",
        description: "mystery candy (dairy-free)",
        price: 1,
        picture: candycane,
        alttext: "a red and white striped candy canes scattered across a red background",
        box: false,
        max_quantity: 15,
    },
    {
        id: 7,
        title: "test candy 4",
        description: "mystery candy (dairy-free)",
        price: 1,
        picture: candycane,
        alttext: "a red and white striped candy canes scattered across a red background",
        box: false,
        max_quantity: 12,
    },
]